Voting_App/Models/ErrorViewModel.cs
namespace Voting_App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Voting_App/Models/Option.cs
namespace Voting_App.Models
{
    public class Option
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public ICollection<Vote>? Votes { get; set; }
    }
}

Voting_App/Models/User.cs
namespace Voting_App.Models
{
    public class User
    {
        public int Id { get; set; }
        public string? Email { get; set; }
        public string? PasswordHash { get; set; }
    }
}

Voting_App/Models/Vote.cs
namespace Voting_App.Models
{
    public class Vote
    {
        public int Id { get; set; }
        public User? User { get; set; }
        public Option? Option { get; set; }
    }
}

Voting_App/ViewModels/ErrorViewModel.cs
namespace Voting_App.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Voting_App/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Voting_App.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string? Email { get; set; }
        [Required]
        public string? Password { get; set; }
    }
}

Voting_App/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Voting_App.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        
        [Required]
        public string? Password { get; set; }
        
        [Required]
        [Compare("Password")]
        public string? ConfirmPassword { get; set; }
    }
}

Voting_App/ViewModels/VoteViewModel.cs
using Voting_App.Services.Voting;

namespace Voting_App.ViewModels
{
    public class VoteViewModel
    {
        public IEnumerable<OptionData>? OptionsData { get; set; }

        public bool HasUserVoted { get; set; }

        public int ChosenOptionId {  get; set; }
    }
}

Voting_App/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Voting_App.ViewModels;
using Voting_App.Services.Authentication;
using Voting_App.Services.Exceptions;

namespace Voting_App.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthenticationService _authenticationService;

        public AuthenticationController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel viewModel)
        {
            if (ModelState.IsValid == false)
                return View(viewModel);

            try
            {
                await _authenticationService.RegisterUserAsync(viewModel.Email!, viewModel.Password!);
            }
            catch (UserAlreadyRegisteredException)
            {
                return View(viewModel);
            }
            catch
            {
                throw;
            }

            return RedirectToStartPage();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            if (ModelState.IsValid == false)
                return View(viewModel);

            try
            {
                await _authenticationService.Login(viewModel.Email!, viewModel.Password!);
            }
            catch (NotFoundException)
            {
                return View(viewModel);
            }
            catch (IncorrectPasswordException)
            {
                return View(viewModel);
            }
            catch
            {
                throw;
            }
            return RedirectToStartPage();
        }

        public async Task<IActionResult> Logout()
        {
            await _authenticationService.Logout();

            return RedirectToStartPage();
        }

        private IActionResult RedirectToStartPage() => RedirectToAction("Index", "Home");
    }
}

Voting_App/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Voting_App.Models;
using Voting_App.Services.Exceptions;
using Voting_App.Services.Voting;
using Voting_App.ViewModels;

namespace Voting_App.Controllers
{
    public class HomeController : Controller
    {
        private readonly IVoteService _voteService;

        private string UserEmail { get => HttpContext.User.Identity!.Name!; }

        public HomeController(IVoteService voteService)
        {
            _voteService = voteService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult Vote()
        {
            var options = _voteService.GetOptionsData();

            var hasUserVoted = _voteService.HasUserVoted(UserEmail);

            var viewModel = new VoteViewModel()
            {
                OptionsData = options,
                HasUserVoted = hasUserVoted,
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Vote(VoteViewModel viewModel)
        {
            try
            {
                await _voteService.VoteAsync(UserEmail, viewModel.ChosenOptionId);
            }
            catch (UserAlreadyVotedException)
            {
                return RedirectToAction(nameof(Vote));
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch 
            {
                throw;
            }

            return RedirectToAction(nameof(Vote));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Voting_App/Views/Authentication/Login.cshtml
@model LoginViewModel
<h3>
    Login
</h3>

<form method="post" asp-controller="Authentication" asp-action="Login">
    <div class="form-group">
        <label class="sr-only">Email</label>
        <input class="form-control" type="text" asp-for="Email" />
    </div >

    <div class="form-group">
        <label class="sr-only">Password</label>
        <input class="form-control" type="password" asp-for="Password" />
    </div>

    <div>
        <input class="btn btn-primary" type="submit" />
    </div>
</form>

Voting_App/Views/Authentication/Register.cshtml
@model RegisterViewModel
<h3>
    Register
</h3>

<form method="post" asp-controller="Authentication" asp-action="Register">
    <div class="form-group">
        <label class ="sr-only">Email</label>
        <input class="form-control" type="text" asp-for="Email" />
    </div>

    <div class="form-group">
        <label class ="sr-only">Password</label>
        <input class="form-control" type="password" asp-for="Password" />
    </div>

    <div class="form-group">
        <label class="sr-only">Confirm password</label>
        <input class="form-control" type="password" asp-for="ConfirmPassword" />
    </div>

    <div class="form-group">
        <input class="btn btn-primary" type="submit" />
    </div>
</form>

Voting_App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<a class="btn btn-primary" asp-action="Vote" asp-controller="Home">Vote!</a>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Voting_App/Views/Home/Vote.cshtml
@model VoteViewModel

<ul class="list-group">

    @foreach (var option in Model.OptionsData)
    {
        <li class="list-group-item d-flex justify-content-between align-items-center">
            @option.Name

            @if(Model.HasUserVoted)
            {
                <span class="badge bg-primary rounded-pill">
                    @option.VoteCount
                </span>
            }
            else
            {
                <form asp-action="Vote" asp-controller="Home" method="post">
                    <input hidden value="@option.Id" asp-for="ChosenOptionId" />
                    <input class="btn btn-primary" type="submit" value="Vote"/>
                </form>
            }
        </li>
    }
</ul>

Voting_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Voting_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Voting_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Voting_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (User!.Identity!.IsAuthenticated)
                        {
                            <li class ="nav-item">
                                <span class="nav-link text-black">@User.Identity.Name</span>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-danger" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Voting_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>